vault:
  ## Address of the vault server.  This should be a string if it is
  ## present.
  addr: https://vault.dide.ic.ac.uk:8200
  auth:
    ## Authentication type - must be either "token" or the name of a
    ## supported authentication method.  These seem to be poorly
    ## documented in the hvac, but include "github" for github
    ## authentication.
    ##
    ## On a vault client object, see auth.implemented_class_names for
    ## a list, which is currently
    ##
    ##     azure, github, gcp, kubernetes, ldap, mfa, okta
    method: github

## Prefix for container names; we'll use {container_prefix}_(orderly,web)
##
## This is an important configuration option because it cannot be
## overridden by a patch file or by passing options in.
##
## IMPORTANT: If you want to change the prefix, you should stop
## OrderlyWeb, then change the prefix, then start it back up.
## Otherwise OrderlyWeb will not take down the required containers
## before starting back up.
container_prefix: packit

## Set this flag to true to prevent use of --volumes in the cli to remove
## volumes on stop
protect_data: true

## The name of the docker network that containers will be attached to.
## If you want to proxy OrderlyWeb to the host, you will need to
## arrange a proxy on this network, or use dev_mode in the web section
## below.
network: packit_nw

## Docker org for images
repo: mrcide

## Names of the docker volumes to use:
##
## outpack: stores the outpack metadata
## proxy_logs: stores logs from the reverse proxy (only used if proxy is given)
## (More volumes are anticipated as the tool develops)
volumes:
  outpack: packit_outpack_volume
  proxy_logs: packit_proxy_logs

## If running a proxy directly, fill this section in.  Otherwise you
## are responsible for proxying the application out of the docker
## network
proxy:
  enabled: true
  ssl:
    ## This section describes how to get the certificate in.  We
    ## support two sources:
    ##
    ## 1. self signed certificates - just leave this section blank
    ##
    ## 2. certificates from strings - include the strings directly in
    ##    the keys here, or more likely use a VAULT:<path>:<key>
    ##    string to extract them from the vault.
    certificate: VAULT:secret/packit/ssl/dev/cert:value
    key: VAULT:secret/packit/ssl/dev/key:value
  hostname: packit-dev.dide.ic.ac.uk
  port_http: 80
  port_https: 443
  image:
    name: packit-proxy
    tag: main

outpack:
  ## Initialise an outpack directory by cloning from github
  initial:
    ##  If using a private repo, then use an ssh url and provide ssh keys in the
    ## "ssh" section above.
    ##
    ## This points at the malaria repo for now, later we'll point it
    ## elsewhere, and in general this part of the configuration is
    ## likely to change.
    url: https://github.com/mrc-ide/malaria-sites-orderly
  server:
    name: outpack_server
    tag: main
  migrate:
    name: outpack.orderly
    tag: main

packit:
  api:
    name: packit-api
    tag: main
  app:
    name: packit
    tag: main
  db:
    name: packit-db
    tag: main
    user: packituser
    password: changeme
